version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    ports:
      - 32000:80
      - 32001:443
    build:
      context: .
      dockerfile: Api/Dockerfile
    environment:
      "PIPELINE_NAME" : "Dzoni"
